### ISSUE TITLE
框架是否支持多机多卡训练

### ISSUE THREAD

**Issue by Danield21** [TinyLLaVA/TinyLLaVA_Factory#155]
作者您好！
感谢您的优秀工作，请问一下此框架支持多机多卡的训练嘛?

目前在单机八卡的A800上，我可以成功训练。但是当我用 4台8卡A800训练的时候，却报错如下
 
```
Traceback (most recent call last):
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/anaconda3/envs/mmdistill/lib/python3.10/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
  File "/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
tinyllava/train/train.py FAILED
----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-17_15:22:30
  host      : VM-0-38-tencentos
  rank      : 12 (local_rank: 4)
  exitcode  : -6 (pid: 106)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 106
====================================================
:22:34.801000 140576871319360 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -6) local_rank: 4 (pid: 108) of binary: /mllm/anaconda3/envs/mmdistill/bin/python
Traceback (most recent call last):
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mllm/anaconda3/envs/mmdistill/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
tinyllava/train/train.py FAILED
----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-17_15:22:30
  host      : VM-0-102-tencentos
  rank      : 4 (local_rank: 4)
  exitcode  : -6 (pid: 108)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 108
====================================================
[I1217 15:22:34.352644390 TCPStoreLibUvBackend.cpp:115] [c10d - debug] Read callback failed. code:-4095 name:EOF desc:end of file
[I1217 15:22:34.352749398 TCPStoreLibUvBackend.cpp:1002] [c10d - debug] Store exit requested

[I1217 15:22:34.352761090 TCPStoreLibUvBackend.cpp:1070] [c10d - debug] UV main loop done: res:1
[I1217 15:22:34.352826453 TCPStoreLibUvBackend.cpp:1076] [c10d - debug] Walking live handles prior to closing clients
[I1217 15:22:34.352834689 TCPStoreLibUvBackend.cpp:1059] [c10d - debug] UV live handle type 12 active:1 is-closing:0
[I1217 15:22:34.352840330 TCPStoreLibUvBackend.cpp:1059] [c10d - debug] UV live handle type 12 active:1 is-closing:0
[I1217 15:22:34.352887749 TCPStoreLibUvBackend.cpp:1086] [c10d - debug] Walking live handles after closing clients
[I1217 15:22:34.352893310 TCPStoreLibUvBackend.cpp:1059] [c10d - debug] UV live handle type 12 active:0 is-closing:1
[I1217 15:22:34.352897067 TCPStoreLibUvBackend.cpp:1059] [c10d - debug] UV live handle type 12 active:0 is-closing:1
[I1217 15:22:34.352902006 TCPStoreLibUvBackend.cpp:1095] [c10d] uv_loop_close failed with:-16 errn:EBUSY desc:resource busy or locked
[I1217 15:22:34.352943645 TCPStoreLibUvBackend.cpp:1105] [c10d] uv_loop cleanup finished.
```

请问这是否正常呢

**Comment by ZhangXJ199** [comment]
可能不支持，我们只在单机多卡上进行过实验

**Comment by Danield21** [comment]
感谢您的回复，
通过debug发现是集群环境的问题，目前已可以在2机16卡A800上running
