### ISSUE TITLE
Missing key "lm_head.weight" in GemmaForCausalLM when loading lora finetuned TinyLLaVA-Gemma-SigLIP-2.4B

### ISSUE THREAD

**Issue by Yuki-Kokomi** [TinyLLaVA/TinyLLaVA_Factory#88]
When attempting to merge LoRA weights into the TinyLLaVA-Gemma-SigLIP-2.4B model, I encountered a RuntimeError due to a missing key lm_head.weight in the GemmaForCausalLM state_dict. The specific error traceback is as follows:
```
Traceback (most recent call last):
  File "/../TinyLLaVA_Factory/merge_lora_weights.py", line 27, in <module>
    merge_lora(args)
  File "/../TinyLLaVA_Factory/merge_lora_weights.py", line 14, in merge_lora
    model, tokenizer,  image_processor, context_len = load_pretrained_model(args.model_path)
  File "/../TinyLLaVA_Factory/tinyllava/model/load_model.py", line 45, in load_pretrained_model
    model.language_model.load_state_dict(language_model_ckp)
  File "/../miniforge3/envs/tinyllava_factory/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GemmaForCausalLM:
        Missing key(s) in state_dict: "lm_head.weight".
```
This issue seems similar to [vllm-project/vllm#3323](https://github.com/vllm-project/vllm/issues/3323). Any insights or solutions to resolve the missing "lm_head.weight" key would be greatly appreciated.

**Comment by ggcr** [comment]
This just happened to me also. After the pre-training phase I am trying to perform inference however seems there is a miss-match between the saved model on `/<model_path>/language_model/pytorch_model.bin`

**Comment by ggcr** [comment]
A quick work around for now would be to follow the solkution made on the issue https://github.com/vllm-project/vllm/issues/3323 linked by @Yuki-Kokomi, by copying the `embed_token` weight onto the `lm_head`:

```python
        language_model_ckp_path = os.path.join(model_name_or_path, 'language_model/pytorch_model.bin')
        language_model_ckp = load_base_ckp_for_lora(language_model_ckp_path)

        # This line is what does the trick
        language_model_ckp['lm_head.weight'] = language_model_ckp['model.embed_tokens.weight']

        model.language_model.load_state_dict(language_model_ckp)
 ```

However, I am not able to qualitatively validate that this fix works fine.

**Comment by Yuki-Kokomi** [comment]
Thank you @ggcr for the solution. It works perfectly.

**Comment by ggcr** [comment]
I can provide a PR by doing this checking if the LLM backbone used is Gemma if the authors want.

**Comment by YingHuTsing** [comment]
> I can provide a PR by doing this checking if the LLM backbone used is Gemma if the authors want.

Hi, we do encourage you to initiate a PR!

**Comment by Danield21** [comment]
Hi, the same problem happens when using  Qwen2-1.5B-Instruct as the llm part. 

It seems to be normal because some llms (like qwen2 0.5B/1.5B) use the `tied word embedding' technique, where the 'lm_head.weight' and 'model.embed_tokens.weight' are tied together for parameters efficiency.

 I understand it after checking the issue for qwen2: [qwen2 1.5B not having lm_head](https://github.com/QwenLM/Qwen2.5/issues/733), may it also makes sense for Gemma.

**Comment by Danield21** [comment]
> Hi, the same problem happens when using Qwen2-1.5B-Instruct as the llm part.
> 
> It seems to be normal because some llms (like qwen2 0.5B/1.5B) use the `tied word embedding' technique, where the 'lm_head.weight' and 'model.embed_tokens.weight' are tied together for parameters efficiency.
> 
> I understand it after checking the issue for qwen2: [qwen2 1.5B not having lm_head](https://github.com/QwenLM/Qwen2.5/issues/733), may it also makes sense for Gemma.

![WeChatdb61322288342043ce6c38928c9d6a29](https://github.com/user-attachments/assets/32adfe27-9bec-465a-8ced-b2d0d961d842)
![WeChat281f7157710c06b85db0ec01bcab77ca](https://github.com/user-attachments/assets/5fb116b4-ef95-471d-9976-6f100000cac6)

As seen from two pictures, qwen2-1.5B uses the  `tied word embedding' technique, but qwen2-7B does not.
